- name: Install Docker Debian
  apt:
    name: docker.io
    state: present
  when: ansible_os_family == 'Debian'

- name: Install Docker RedHat
  package:
    name: docker
    state: present
  when: ansible_os_family == 'RedHat'

- name: Start Docker
  service:
    name: docker
    state: started
    enabled: yes

- name: Add user to docker group
  user:
    name: ansible
    groups: docker
    append: yes

- name: Install Nexus Repository
  tags: nexus_repository
  docker_container:
    name: nexus_repository
    image: sonatype/nexus3
    state: started
    ports:
      - "8081:8081"
      - "8082:8082"
    volumes:
      - nexus_repository_data:/nexus-data
    restart_policy: always
    healthcheck:
      test: "curl --fail http://localhost:8081/"
      interval: 30s
      timeout: 10s
      retries: 5
