- name: ngrok_add_token
  tags: ngrok
  command: /usr/local/bin/ngrok config add-authtoken {{ lookup('file', '/home/shhrrtnvr/.ngrok_token')}}

# Run the ngrok command in the background and save process ID to a file
- name: ngrok_tunnel
  tags: ngrok
  shell: "/usr/local/bin/ngrok http --domain={{ DOMAIN }} 8111 > /dev/null & echo $! > /tmp/ngrok.pid"
