- name: Install ngrok
  tags: ngrok
  unarchive:
    src: https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.tgz
    dest: /usr/local/bin
    remote_src: yes
    mode: 0755
    owner: root
    group: root
